.TH SYSTEMACT 1 systemact\-VERSION
.SH NAME
systemact \- logout menu backend
.SH SYNOPSIS
.B systemact
.RB [ options ]
.IR actions
.SH DESCRIPTION
systemact is a backend for logout and power menus with command customization to work on any setup.
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Print brief usage information to standard output and exit.
.TP
.B "\-N, \-\-no\-dialog"
show no confirmation dialog, always perform action.
.TP
.B "\-V, \-\-version"
show program version.
.TP
.B "\-d, \-\-debug"
show debug output.
.TP
.B "\-n, \-\-dryrun"
run the program but perform no action.
.SH ACTIONS
.TP
.B "lock"
Lock the screen with a configurable command.
.TP
.B "logout"
Terminate the session and log out with a configurable command.
.TP
.B "shutdown, poweroff"
Power off the system.
.TP
.B "reboot, restart"
Restart the system.
.TP
.B "suspend, sleep"
Suspend the system with a configurable command.
.SH CONFIGURATION
.P
The whole reason of systemact is to have flexibility and provide a backend command for a logout menu
that works across multiple setups and software stacks, for that purpose many of the actions are done
through configurable commands so that the users can specify whatever command they want for their
setup without having to hardcode it anywhere in the software that is actually providing the ui, tho
systemact will try to default to widely supported commands if the user doesn't specify custom ones.
.P
For the purpose of working with multiple software stacks systemact defines the
.B $ctl
variable that points to a seat control facility, usually
.B systemctl
or
.B loginctl
which are provided by systemd and elogind respectively, the ctl command is determined by systemact
at runtime by checking the available commands in the system via command -v, it used to check the
symlink in
.B /sbin/init
if it contains the string
.B systemd
but the new method is more reliable as some setups may be using systemd as a service and login
manager but not as init, for example using runit to provide pid1, this new method also allows us to
check for the usage of consolekit.
.P
It is important to note that systemact does NOT do any validation for the custom commands as there
is no easy way to test those, so in that case whatever goes wrong with those is the user's fault.
.P
The following options are available:
.TP
.B logoutcmd
Command used to logout the session, by default
.B do_ctl
terminate-session
.B ${XDG_SESSION_ID}
.TP
.B lockcmd
Command used to lock the session, by default
.B do_ctl
lock-session
.B ${XDG_SESSION_ID}
.TP
.B suspend_method
The method by which the system will be suspended, you can choose between suspend, hybrid-sleep and
suspend-then-hibernate,
by default
.B do_ctl
suspend
.TP
.B timeout
The time without user interaction it takes for the action (logout, shutdown, reboot, suspend) to
run, the time is capped to minimum 15 seconds and maximum 240 seconds.
.SH FUNCTION OVERRIDES
Internally systemact uses a scheme of wrapper functions to offhand the work, we have 2 wrappers of
note which are
.B do_ctl
and
.B call
.TP
.B do_ctl
a wrapper command that allows us to send action commands onto a login manager handler, such as the
one for (e)logind or consolekit, it is concerned with receiving the actions like: lock-session,
terminate-session, poweroff, reboot, suspend, etc...
.TP
.B call
a wrapper command that checks if an override for the requested function exists and if it does it
proceeds to run it, the override function is expected to be in the form of <cmd>_override, so for
the do_lock function call would look for a function called do_lock_override.
.TP
.B do_sleep
a wrapper function that handles the
.B suspend_method
variable and offhands the action to one of the following functions: do_suspend, do_hibernate,
do_hybrid_sleep, do_suspend_then_hibernate
.P
The following functions are available for override: do_lock, do_logout, do_poweroff, do_reboot,
do_sleep, do_suspend, do_hibernate, do_hybrid_sleep, do_suspend_then_hibernate

In spite of the name
.B config.rc
the config file for systemact is a simple text file that is loaded as if it were a shell script,
therefore you should be able to write overrides for the functions as simple posix shell functions,
you should be able to utilize systemact's internal functions inside your custom overrides like the
do_ctl function, for example in order to add hooks onto do_<action> functions like this:

do_lock_override () {
    if [ -z "$DRYRUN" ]; then
        dbgprint "pausing all media players"
        playerctl -a pause
        # in this case the do_ctl function was okay
        do_ctl lock-session "${XDG_SESSION_ID}"
    fi

}

As you can see in the example making use of the internal dbgprint function and checking for the
value of the
.IR $DRYRUN
var are encouraged for your custom overrides so that they can work seamlessly with the program's
dryrun and debug options.

For the do_<action> functions are rather simple and their internals are as follows:

.IR do_ctl
() {
    action="$1"
    shift
    dbgprint "handling $action with $ctl"
    case "$ctl" in
        *systemctl|*loginctl)
            systemloginctl_handler "$action" "$@"
            ;;
        consolekit)
            consolekit_handler "$action" "$@"
            ;;
    esac

}

.IR do_lock
() {
    # check if a lock command was defined in config
    if [ -z "$lockcmd" ]; then
        # default
        do_ctl lock-session "${XDG_SESSION_ID}"
    else
        dbgprint "locking with '$lockcmd'"
        if [ -z "$DRYRUN" ]; then
            echo "$lockcmd"
        fi
    fi

}

.IR do_logout
() {
    # check if a logout command was defined in config
    if [ -z "$logoutcmd" ]; then
        # default
        do_ctl terminate-session "${XDG_SESSION_ID}"
    else
        dbgprint "logging out with '$lockcmd'"
        if [ -z "$DRYRUN" ]; then
            echo "$logoutcmd"
        fi
    fi

}

.IR do_poweroff
() { do_ctl poweroff }

.IR do_reboot
() { do_ctl reboot }

.IR do_suspend
() { do_ctl suspend }

.IR do_hibernate
() { do_ctl hibernate }

.IR do_hybrid_sleep
() { do_ctl hybrid-sleep }

.IR do_suspend_then_hibernate
() { do_ctl suspend }

.IR do_sleep
() {
    # check if a suspend method was defined in config
    if [ -z "$suspend_method" ]; then
        # default
        suspend_method="suspend"
    fi
    case "$suspend_method" in
        suspend)
            call do_suspend
            ;;
        hibernate)
            call do_hibernate
            ;;
        hybrid-sleep)
            call do_hybrid_sleep
            ;;
        suspend-then-hibernate)
            call do_suspend_then_hibernate
            ;;
        *)
            call do_suspend
            ;;
    esac

}

.SH AUTHOR
.EX
eylles                 <ed.ylles1997 at gmail.com>
.EE
.SH HOMEPAGE
.TP
Source code:
.EE
https://github.com/eylles/systemact
.EX
