.TH SYSTEMACT 1 systemact\-VERSION
.SH NAME
systemact \- logout menu backend
.SH SYNOPSIS
.B systemact
.RB [ options ]
.IR actions
.SH DESCRIPTION
systemact is a backend for logout and power menus with command customization to work on any setup.
.P
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Print brief usage information to standard output and exit.
.SH ACTIONS
.TP
.B "lock"
Lock the screen with a configurable command.
.TP
.B "logout"
Terminate the session and log out with a configurable command.
.TP
.B "shutdown, poweroff"
Power off the system.
.TP
.B "reboot, restart"
Restart the system.
.TP
.B "suspend, sleep"
Suspend the system with a configurable command.
.SH AUTHOR
.EX
eylles                 <ed.ylles1997 at gmail.com>
.EE
.SH HOMEPAGE
.TP
Source code:
.EE
https://github.com/eylles/systemact
.EX
